# tell docker what version of the docker-compose.yml we're using
version: '3.7'

# start the services section
services:

  docker-nginx:
    restart: always
    build:
      context: ./nginx
    # defines the port mapping
    # corresponds to the "-p" flag
    ports:
      - "80:80"
    tty: true
    volumes:
      - ../:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - docker-php-fpm
      - docker-db

  docker-php-fpm:
    restart: always
    environment:
      - DEBUG_PHP
      - HOST_IP
      - DEBUG
      - REMOTE_HOST
    build:
      context: ./php-fpm
    tty: true
    volumes:
      - ../:/var/www

  docker-db:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: 'database'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '6677:3306'
    # Where our data will be persisted
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 7070:80
    environment:
      PMA_HOST: docker-db
      PMA_PORT: 3306
      PMA_USER: 'user'
      PMA_PASSWORD: 'password'
