controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_controllers:
    resource: ../src/Api/Entrypoint/Http/
    type: annotation